AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Manga/Novels RSS Generator

Resources:
  RssFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: lambda/app.handler
      Runtime: ruby2.7
      MemorySize: 512
      Timeout: 10
      Environment: {}
      Events:
        Feed:
          Type: Api
          Properties:
            Path: '/{contentProvider}/{contentId}'
            Method: GET
